name: CI

on:
  push:
    branches:
    - main
    tags:
    - v*
    paths-ignore:
    - docs/**
    - LICENSE
    - '**.md'
  pull_request:
    branches:
    - main
    paths-ignore:
    - docs/**
    - LICENSE
    - '**.md'

jobs:
  build:

    name: "Build & package"
    runs-on: ubuntu-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v2

    - name: Clean
      run: |
        dotnet clean --configuration Release
        dotnet nuget locals all --clear

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: |
        dotnet test test/AspNetCoreJsModules.Tests/AspNetCoreJsModules.Tests.csproj --configuration Release --no-build --logger trx

    - name: Test report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test results
        path: "**/*.trx"
        reporter: dotnet-trx

    - name: Package
      run: dotnet pack src/AspNetCoreJsModules/AspNetCoreJsModules.csproj --configuration Release --no-build
      env:
        MINVERBUILDMETADATA: ${{ env.GITHUB_RUN_NUMBER }}

    - name: Publish package artifact
      uses: actions/upload-artifact@v3
      with:
        name: AspNetCoreJsModules.nupkg
        path: src/AspNetCoreJsModules/bin/Release/*.nupkg
        if-no-files-found: error


  release:

      name: "Release"
      runs-on: ubuntu-latest
      needs: build
      if: startsWith(github.ref, 'refs/tags/v')

      steps:
      - name: Download package artifact
        uses: actions/download-artifact@v2
        with:
          name: AspNetCoreJsModules.nupkg

      - name: Publish package to NuGet
        run: dotnet nuget push **/*.nupkg --api-key $NUGET_TOKEN --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
